"use client";
import { useEffect, useState } from "react";
import type { LeadRegister } from "@/lib/lead-register";
const format=(value:string)=>value?new Date(value).toLocaleString("en-GB",{timeZone:"Europe/London",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"Unknown";
export function LeadRegisterPanel(){
 const [data,setData]=useState<LeadRegister|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("forms"),[search,setSearch]=useState(""),[limit,setLimit]=useState(50);
 useEffect(()=>{const c=new AbortController();fetch("/api/lead-register",{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d.data);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 async function refresh(){setBusy(true);setError("");try{const r=await fetch("/api/lead-register",{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d.data);}catch(e){setError(e instanceof Error?e.message:"Refresh failed");}finally{setBusy(false);}}
 const [viewedAt]=useState(()=>Date.now());
 const cutoff=Date.parse(data?.checkedAt || "")-30*86400000;
 const recent=data?.entries.filter(e=>Date.parse(e.contactCreated)>=cutoff||Date.parse(e.lastConversationAt)>=cutoff||e.submissions.some(s=>Date.parse(s.at)>=cutoff))??[];
 const formLeads=recent.filter(e=>!e.test&&e.submissions.some(s=>Date.parse(s.at)>=cutoff));
 const rows=(filter==="archive"?data?.entries??[]:recent).filter(e=>filter==="tests"?e.test:!e.test).filter(e=>filter==="forms"?e.submissions.some(s=>Date.parse(s.at)>=cutoff):filter==="unbooked"?e.submissions.some(s=>Date.parse(s.at)>=cutoff)&&!e.appointments.length:true).filter(e=>(e.name+" "+e.source+" "+e.tags.join(" ")).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>(b.submissions.at(-1)?.at||b.contactCreated).localeCompare(a.submissions.at(-1)?.at||a.contactCreated));
 return <section className="mb-6 rounded-xl border p-5" aria-label="Saved enquiry register">
 <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Saved enquiry register</h2><button className="rounded border px-3 py-2 text-sm disabled:opacity-50" disabled={busy} onClick={refresh}>{busy?"Checking HighLevel…":"Refresh and save enquiries"}</button></div>
 <p className="mt-2 text-sm text-muted-foreground">One row per HighLevel contact. Enquiry and booking submissions are grouped together. Other new or recently active CRM contacts are included separately; they are not automatically sales leads.</p>
 {error&&<p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}
 {!data&&!error&&<p className="mt-3 text-sm">No saved register loaded yet. Refresh to import the last 90 days.</p>}
 {data&&<><div className="my-4 grid grid-cols-2 gap-4 md:grid-cols-4">{[["People enquiring · 30 days",formLeads.length],["Form submissions · 30 days",formLeads.reduce((n,e)=>n+e.submissions.filter(s=>Date.parse(s.at)>=cutoff).length,0)],["No booking found",formLeads.filter(e=>!e.appointments.length).length],["CRM records missing",recent.filter(e=>!e.contactFound).length]].map(([label,value])=><div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></div>)}</div>
 <p className="text-xs text-muted-foreground">Saved {format(data.checkedAt)} (UK time). {viewedAt-Date.parse(data.checkedAt)>2*3600000?"Refresh overdue — this register may be stale. ":""}Tests excluded from headline counts. “Contacted” is a CRM tag, not proof of attendance. Booking checks cover the sales calendar from {format(new Date(Date.parse(data.checkedAt)-90*86400000).toISOString())} to {format(data.calendarEnd)}.</p>
 <div className="my-4 flex flex-wrap gap-2"><label className="sr-only" htmlFor="lead-filter">Show enquiries</label><select id="lead-filter" className="rounded border bg-background p-2 text-sm" value={filter} onChange={e=>setFilter(e.target.value)}><option value="forms">Website enquiries · 30 days</option><option value="unbooked">No booking found · 30 days</option><option value="all">All new / active CRM contacts · 30 days</option><option value="tests">Tagged test records · 30 days</option><option value="archive">All saved contacts</option></select><input aria-label="Search saved enquiries" className="rounded border bg-background p-2 text-sm" placeholder="Search name, source or tag" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b">{["Contact","Latest enquiry / created","Source","Submissions","Follow-up","Booking"].map(x=><th key={x} className="p-2 font-medium">{x}</th>)}</tr></thead><tbody>{rows.slice(0,limit).map(e=><tr key={e.contactId} className="border-b align-top"><td className="p-2"><a className="font-medium underline" target="_blank" rel="noreferrer" href={`https://app.gohighlevel.com/v2/location/${encodeURIComponent(data.locationId || "")}/contacts/detail/${encodeURIComponent(e.contactId)}`}>{e.name}</a>{e.test&&<span className="block text-xs">Test record</span>}{!e.contactFound&&<span className="block text-red-600">CRM contact unavailable</span>}{e.checkedAt!==data.checkedAt&&<span className="block text-xs">Previously saved · last checked {format(e.checkedAt)}</span>}</td><td className="p-2 whitespace-nowrap">{format(e.submissions.at(-1)?.at||e.contactCreated)}</td><td className="p-2">{e.source}{e.lastMessageChannel&&<p className="text-xs">Latest conversation: {e.lastMessageChannel} · {format(e.lastConversationAt)}</p>}<span className="block text-xs text-muted-foreground">{e.metaSource?`Attribution: ${e.metaSource}`:"Attribution unavailable"}</span></td><td className="p-2">{e.submissions.length}<details><summary className="text-xs cursor-pointer">View dates</summary>{e.submissions.map(s=><p key={s.id} className="mt-1 text-xs">{format(s.at)} · {s.page||"Page unknown"}</p>)}</details></td><td className="p-2">{e.tags.some(t=>t.toLowerCase()==="contacted")?"Tagged contacted":"No contacted tag"}<p className="mt-1 text-xs text-muted-foreground">{e.tags.join(", ")}</p></td><td className="p-2">{e.appointments.length?e.appointments.map(a=><p key={a.id}>{format(a.at)} · {a.status}</p>):"No booking found in checked window"}</td></tr>)}</tbody></table>{rows.length>limit&&<button className="my-3 rounded border p-2 text-sm" onClick={()=>setLimit(n=>n+50)}>Show 50 more ({rows.length-limit} remaining)</button>}{!rows.length&&<p className="py-4 text-sm">No records match this view.</p>}</div>
 <p className="mt-3 text-xs text-muted-foreground">Saved in the dashboard database; HighLevel remains the source record. Refreshes preserve older enquiries and the last complete result on failure. An hourly import checks the previous 90 days. This cannot recover messages never delivered or submissions never accepted by HighLevel.</p></>}
 </section>;
}
