"use client";
import { useEffect, useState } from "react";
import type { LeadRegister } from "@/lib/lead-register";
import { leadEvidence, leadRegisterChanges } from "@/lib/lead-register-view";
const format=(value:string)=>value?new Date(value).toLocaleString("en-GB",{timeZone:"Europe/London",day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}):"Unknown";
export function LeadRegisterPanel(){
 const [data,setData]=useState<LeadRegister|null>(null),[error,setError]=useState(""),[refreshResult,setRefreshResult]=useState(""),[busy,setBusy]=useState(false),[filter,setFilter]=useState("enquiries"),[search,setSearch]=useState(""),[limit,setLimit]=useState(50);
 useEffect(()=>{const c=new AbortController();fetch("/api/lead-register",{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d.data);}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[]);
 async function refresh(){
  setBusy(true);setError("");setRefreshResult("");
  try{
   const r=await fetch("/api/lead-register",{method:"POST",cache:"no-store"});const d=await r.json();
   if(!r.ok)throw Error(d.error||"Refresh failed");
   const updated=d.data as LeadRegister;
   const changes=leadRegisterChanges(data,updated);
   setData(updated);
   window.dispatchEvent(new CustomEvent<LeadRegister>("lead-register:updated",{detail:updated}));
   setRefreshResult(changes?`Refresh complete at ${format(updated.checkedAt)} (UK time). ${changes.newLeadContacts} additional ${changes.newLeadContacts===1?"contact is":"contacts are"} visible in this view, with ${changes.newFormSubmissions} new form submission ${changes.newFormSubmissions===1?"receipt":"receipts"} since this page loaded.`:`Refresh complete at ${format(updated.checkedAt)} (UK time). The saved register is ready.`);
  }catch(e){setError(e instanceof Error?e.message:"Refresh failed");}finally{setBusy(false);}
 }
 const [viewedAt,setViewedAt]=useState(()=>Date.now());
 useEffect(()=>{const timer=window.setInterval(()=>setViewedAt(Date.now()),60_000);return()=>window.clearInterval(timer);},[]);
 const cutoff=Date.parse(data?.checkedAt || "")-30*86400000;
 const recent=data?.entries.filter(e=>Date.parse(e.contactCreated)>=cutoff||Date.parse(e.lastConversationAt)>=cutoff||e.submissions.some(s=>Date.parse(s.at)>=cutoff))??[];
 const formLeads=recent.filter(e=>leadEvidence(e,cutoff)==="form");
 const formOriginLeads=recent.filter(e=>leadEvidence(e,cutoff)==="form-origin");
 const crmLeads=recent.filter(e=>leadEvidence(e,cutoff)==="crm-lead");
 const enquiryRows=recent.filter(e=>leadEvidence(e,cutoff));
 const rows=(filter==="archive"?data?.entries??[]:recent)
  .filter(e=>filter==="tests"?e.test:!e.test)
  .filter(e=>filter==="enquiries"?leadEvidence(e,cutoff)!==null:filter==="forms"?leadEvidence(e,cutoff)==="form":filter==="form-origin"?leadEvidence(e,cutoff)==="form-origin":filter==="crm-leads"?leadEvidence(e,cutoff)==="crm-lead":filter==="unbooked"?leadEvidence(e,cutoff)!==null&&!e.appointments.length:true)
  .filter(e=>(e.name+" "+e.source+" "+e.tags.join(" ")).toLowerCase().includes(search.toLowerCase()))
  .sort((a,b)=>(b.submissions.at(-1)?.at||b.contactCreated).localeCompare(a.submissions.at(-1)?.at||a.contactCreated));
 return <section className="mb-6 rounded-xl border p-5" aria-label="Saved enquiry register">
 <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Saved enquiry register</h2><button className="rounded border px-3 py-2 text-sm disabled:opacity-50" disabled={busy} onClick={refresh}>{busy?"Checking HighLevel…":"Refresh and save enquiries"}</button></div>
 <p className="mt-2 text-sm text-muted-foreground">This view separates form submission receipts, contacts attributed to the configured form without a receipt, and contacts tagged “new lead” in HighLevel. Check a contact’s source record before treating it as a new sales enquiry.</p>
 {busy&&<p role="status" className="mt-3 text-sm">Checking HighLevel and saving the complete result…</p>}
 {refreshResult&&<p role="status" className="mt-3 rounded border border-green-600/30 bg-green-600/5 px-3 py-2 text-sm">{refreshResult}</p>}
 {error&&<p role="alert" className="mt-3 text-sm text-red-600">{error}</p>}
 {!data&&!error&&<p className="mt-3 text-sm">Loading saved enquiries…</p>}
 {data&&<><div className="my-4 grid grid-cols-2 gap-4 md:grid-cols-5">{[["People with form receipts · 30 days",formLeads.length],["Form submissions · 30 days",formLeads.reduce((n,e)=>n+e.submissions.filter(s=>Date.parse(s.at)>=cutoff).length,0)],["Form attribution, no receipt · 30 days",formOriginLeads.length],["Other CRM leads · 30 days",crmLeads.length],["No sales-calendar booking · 30 days",enquiryRows.filter(e=>!e.appointments.length).length]].map(([label,value])=><div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></div>)}</div>
 {formOriginLeads.length>0&&<p role="status" className="mb-3 rounded border border-amber-600/30 bg-amber-600/5 px-3 py-2 text-sm">HighLevel attributes {formOriginLeads.length} recent contact{formOriginLeads.length===1?"":"s"} to the configured form but returned no matching submission receipt. Form submission totals omit these contacts; open their HighLevel records to review them.</p>}
 <p className="text-xs text-muted-foreground">Saved {format(data.checkedAt)} (UK time). {viewedAt-Date.parse(data.checkedAt)>2*3600000?"Refresh overdue — this register may be stale. ":""}Tests excluded from headline counts. “Contacted” is a CRM tag, not proof of attendance. Booking checks cover the sales calendar from {format(new Date(Date.parse(data.checkedAt)-90*86400000).toISOString())} to {format(data.calendarEnd)}.</p>
 <div className="my-4 flex flex-wrap gap-2"><label className="sr-only" htmlFor="lead-filter">Show enquiries</label><select id="lead-filter" className="rounded border bg-background p-2 text-sm" value={filter} onChange={e=>setFilter(e.target.value)}><option value="enquiries">Enquiries to review · 30 days</option><option value="forms">Form submission receipts · 30 days</option><option value="form-origin">Form attribution, receipt missing · 30 days</option><option value="crm-leads">Other CRM leads · 30 days</option><option value="unbooked">No sales-calendar booking · 30 days</option><option value="all">All new / active CRM contacts · 30 days</option><option value="tests">Tagged test records · 30 days</option><option value="archive">All saved contacts</option></select><input aria-label="Search saved enquiries" className="rounded border bg-background p-2 text-sm" placeholder="Search name, source or tag" value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b">{["Contact","Latest enquiry / created","Source","Submissions","Follow-up","Booking"].map(x=><th key={x} className="p-2 font-medium">{x}</th>)}</tr></thead><tbody>{rows.slice(0,limit).map(e=><tr key={e.contactId} className="border-b align-top"><td className="p-2"><a className="font-medium underline" target="_blank" rel="noreferrer" href={`https://app.gohighlevel.com/v2/location/${encodeURIComponent(data.locationId || "")}/contacts/detail/${encodeURIComponent(e.contactId)}`}>{e.name}</a>{leadEvidence(e,cutoff)==="form-origin"&&<span className="block text-xs text-amber-700">Configured-form attribution · submission receipt missing</span>}{leadEvidence(e,cutoff)==="crm-lead"&&<span className="block text-xs text-amber-700">CRM lead tag · form origin unverified</span>}{e.tags.some(t=>t.toLowerCase()==="currentclient")&&<span className="block text-xs">Tagged current client</span>}{e.test&&<span className="block text-xs">Test record</span>}{!e.contactFound&&<span className="block text-red-600">CRM contact unavailable</span>}{e.checkedAt!==data.checkedAt&&<span className="block text-xs">Previously saved · last checked {format(e.checkedAt)}</span>}</td><td className="p-2 whitespace-nowrap">{format(e.submissions.at(-1)?.at||e.contactCreated)}</td><td className="p-2">{e.source}{e.lastMessageChannel&&<p className="text-xs">Latest conversation: {e.lastMessageChannel} · {format(e.lastConversationAt)}</p>}<span className="block text-xs text-muted-foreground">{e.metaSource?`Attribution: ${e.metaSource}`:"Attribution unavailable"}</span></td><td className="p-2">{e.submissions.length}{e.submissions.length>0&&<details><summary className="text-xs cursor-pointer">View dates</summary>{e.submissions.map(s=><p key={s.id} className="mt-1 text-xs">{format(s.at)} · {s.page||"Page unknown"}</p>)}</details>}</td><td className="p-2">{e.tags.some(t=>t.toLowerCase()==="contacted")?"Tagged contacted":"No contacted tag"}<p className="mt-1 text-xs text-muted-foreground">{e.tags.join(", ")}</p></td><td className="p-2">{e.appointments.length?e.appointments.map(a=><p key={a.id}>{format(a.at)} · {a.status}</p>):"No booking found in checked window"}</td></tr>)}</tbody></table>{rows.length>limit&&<button className="my-3 rounded border p-2 text-sm" onClick={()=>setLimit(n=>n+50)}>Show 50 more ({rows.length-limit} remaining)</button>}{!rows.length&&<p className="py-4 text-sm">No records match this view.</p>}</div>
 <p className="mt-3 text-xs text-muted-foreground">Saved in the dashboard database; HighLevel remains the source record. Refreshes preserve older enquiries and the last complete result on failure. An hourly import checks the previous 90 days. This cannot recover messages never delivered or submissions never accepted by HighLevel.</p></>}
 </section>;
}
